---
title: "mouthwash_sims_plot"
author: "David Gerard"
date: "October 5, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Code to reproduce plot for MS.

```{r}
replace_names <- function(x) {
  x <- stringr::str_replace(x, "pi0_", "")
  x <- stringr::str_replace(x, "auc_", "")
  x <- stringr::str_replace(x, "mse_", "")
  x <- stringr::str_replace(x, "ash_mouthwash", "MOUTHWASH")
  x <- stringr::str_replace(x, "ash_backwash", "BACKWASH")
  x <- stringr::str_replace(x, "ash_(.+)", "\\1+ASH")
  x <- stringr::str_replace(x, "qvalue_(.+)", "\\1+qvalue")
  x <- stringr::str_replace(x, "ruv", "RUV")
  x <- stringr::str_replace(x, "caterr_cal", "CATErr+MAD")
  x <- stringr::str_replace(x, "cate_nccal", "CATEnc+Cal")
  x <- stringr::str_replace(x, "caterr", "CATErr")
  x <- stringr::str_replace(x, "cate", "CATEnc")
  x <- stringr::str_replace(x, "_madcal", "+MAD")
  x <- stringr::str_replace(x, "pvalue_", "")
  x <- stringr::str_replace(x, "ols", "OLS")
  x <- stringr::str_replace(x, "sva", "SVA")
  x <- stringr::str_replace(x, "_norm", "")
}

sims_file <- "/home/david/Code/rcc_copy/projects/reproduce_mouthwash/Output/sims_out/sims_out.RDS"

## pi0 first ------------------------------------------------------------
library(tidyverse)
dat <- as_data_frame(readRDS(file = sims_file))
longdat <- select(dat, nullpi, Nsamp, ncontrols, contains("pi0")) %>%
  gather(key = "Method", value = "pi0hat", pi0_ash_ols:pi0_qvalue_caterr_cal) %>%
  filter(Nsamp == 40, nullpi == 0.9, ncontrols == 100)
longdat$Method <- replace_names(longdat$Method)
msedat <- mutate(longdat, squared_differences = (pi0hat - 0.9) ^ 2) %>%
  group_by(Method) %>%
  summarise(mse = mean(squared_differences))
longdat$Method <- factor(longdat$Method, levels = msedat$Method[order(msedat$mse, decreasing = FALSE)])

pl <- ggplot(data = longdat, mapping = aes(y = pi0hat, x = Method)) +
  geom_boxplot(outlier.size = 0.1) +
  geom_hline(yintercept = 0.9, lty = 2, col = "red") +
  theme_bw() +
  theme(strip.background = element_rect(fill = "white"),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
  ylab("Estimate of Pi0")

  pdf(file = "mouthwash_pi0_box.pdf", colormodel = "cmyk",
      family = "Times", width = 6, height = 4)
  print(pl)
  dev.off()

```


```{r}
sessionInfo()
```
